department/urls.py
from django.urls import path
from .views import *
app_name = 'department'

urlpatterns = [
    path('<int:company_id>/', dashboard, name='dashboard'),
    path('create/<int:compid>/<int:f_id>', dashcreate, name='create'),

    # test route (filter)
    path('filter/<int:company_id>/', filter_view, name='filter_view'),

]

ooms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('department.urls')),
    path('', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

department/models.py
from django.db import models
from django.db.models import DateTimeField
from django.contrib.auth import get_user_model
User = get_user_model()


# creating departments model and table with multiple attributes
class Department(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


# creating company model and table with multiple attributes
class Company(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


# creating company_dept model and table with multiple attributes
class CompanyDept(models.Model):
    compid = models.ForeignKey(Company, on_delete=models.CASCADE)
    deptid = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        try:
            return '{}'.format(self.compid)
        except:
            return None

# creating company_dept_user table with multiple attributes


class CompanyDeptUser(models.Model):
    compid = models.ForeignKey(Company, on_delete=models.CASCADE)
    deptid = models.ForeignKey(Department, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.user)


STATUS = (
    ('wip', 'Work in progress'),
    ('done', 'Complete')
)

SSUBMIT = (
    ('approved', 'Approve'),
    ('wip', 'Not approved')
)

# creating works model and table with multiple attributes


class Work(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    status = models.CharField(choices=STATUS, max_length=50)
    exdate = models.DateTimeField(null=True, blank=True)
    remarks = models.CharField(max_length=50)
    reqno = models.CharField(max_length=50)
    source = models.CharField(max_length=50)
    ssubmit = models.CharField(choices=SSUBMIT, max_length=50)
    fapproval = models.CharField(max_length=50)
    po_wo = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    createdby = models.ForeignKey(
        User, related_name="user_who_create", on_delete=models.CASCADE, null=True, blank=True)
    createdon = models.DateTimeField(null=True, blank=True)
    updatedby = models.ForeignKey(
        User, related_name="user_who_update", on_delete=models.CASCADE, null=True, blank=True)
    updatedon = models.DateTimeField(null=True, blank=True)
    compid = models.ForeignKey(Company, on_delete=models.CASCADE)
    deptid = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

department/forms.py
from django import forms
from .models import *


class WorkForm(forms.ModelForm):
    class Meta:
        model = Work
        fields = ['title', 'description', 'status', 'remarks', 'createdby']

department/views.py
from pprint import pprint
import json
from django.shortcuts import render
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
# dashboard page functionality...


@login_required
# def dashboard(request, company_id):
def dashboard(request, **kwargs):
    # company = Company.objects.get(id=company_id)
    company = Company.objects.get(id=kwargs['company_id'])
    # department = CompanyDept.objects.filter(compid=company_id)
    department = CompanyDept.objects.filter(compid=kwargs['company_id'])

    # debug
    queryset = Work.objects.filter(compid=kwargs['company_id'])

    compdept = CompanyDeptUser.objects.filter(
        user=request.user,
        compid=company
    )
    permission_department_list = []

    for dept in compdept:
        permission_department_list.append(dept.deptid.id)

    for d in department:
        print(d.deptid.id)
    print(permission_department_list)

    context = {
        'department': department,
        'compdept': compdept,
        'permission_department_list': permission_department_list,

        # debug
        'queryset': queryset
    }
    return render(request, 'departments/dashboard.html', context)


# @login_required
@method_decorator(csrf_exempt, name='dispatch')
def dashcreate(request, compid, f_id):
    # print('compid: ', compid)
    # print('f_id: ', f_id)

    if request.method == 'POST':
        title = request.POST['title']
        description = request.POST['description']

        print('49', title, description)

        # print('if')
        # print('title', request.POST.get('title'))
        # print('description', request.POST.get('description'))
        # print('status', request.POST.get('status'))
        # print('remarks', request.POST.get('remarks'))
        # print('createdby', request.POST.get('createdby'))

        # fields = ['title', 'description', 'status', 'remarks', 'createdby']

        form = WorkForm(data=request.POST)
        pprint(form)
        print(form.is_valid())
        # print(form.cleaned_data['title'])

        company = Company.objects.get(id=compid)
        # print('company: ', company)

        department = Department.objects.get(id=f_id)
        # print('department: ', department)

        if form.is_valid():
            work = form.save(commit=False)
            work.createdby = request.user
            work.compid = company
            work.deptid = department
            work.save()
            return redirect('department:dashboard', company_id=compid)
    else:
        form = WorkForm()
        return render(request,'departments/dashcreate.html',{'form':form})


# test view: path('filter/<int:company_id>/', filter_view, name='filter_view'),
@method_decorator(csrf_exempt, name='dispatch')
def filter_view(request, *args, **kwargs):
    queryset = Work.objects.filter(compid=kwargs['company_id'])
    print(queryset)
    template = 'departments/filtered_data.html'
    context = {'queryset': queryset}
    return render(request, template, context)

department/templates/departments/dashboard.html
{% extends 'base.html' %} {% block content %}

    <div class="accordion" id="dash_accordion">
{#        {% for d in department %}#}
        {% for item in queryset %}

            <div class="card">
                <div class="card-header" id="create">

                    <button class="btn btn-d" type="button" data-toggle="collapse" data-target="#{{ item }}"
                            aria-expanded="true">{{ item.deptid.name }}</button>

                    <p>{{ item.title }}</p>

                    <form method="POST" action="{% url 'department:create' item.compid.id  item.deptid.id %}">
                        {#        {% csrf_token %}#}
                        {% if item.deptid.id in permission_department_list %}
                            <input type="submit" class="btn btn-info" value="Create" style="float: right"/>
                        {% endif %}
                    </form>

                </div>

                <div id="{{ item }}" class="collapse" data-parent="#create">
                    <div class="card-body"></div>
                </div>

            </div>

        {% endfor %}

    </div>

{% endblock content %}

department/templates/departments/dashcreate.html
{% extends 'base.html' %} {% block content %}
{% load crispy_forms_tags %}

    <h2>New Task</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

department/templates/departments/filtered_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
</head>

<body>

    <h1>Test Route</h1>
    <hr>
    {% for item in queryset %}
        <h2>Company Name: <span style="color: orangered">{{ item.compid.name }}</span></h2><br>
{#        {{ item.title }}<br>#}
{#        {{ item.createdby }}<br>#}
{#        {{ item.updatedby }}<br>#}
        <h3>Dept. ID: <span style="color: orangered">{{ item.deptid.id }}</span></h3>
        <h3>Dept. Name: <span style="color: orangered">{{ item.deptid.name }}</span></h3>
        <h3>Work Name: <span style="color: orangered">{{ item.title }}</span></h3>
        <hr>
    {% endfor %}


</body>
</html>